name: ML Training Pipeline

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  preparing-data:
    name: Preparing Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Install Poetry
        run: pip install poetry
    
      - name: Install Python version ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
        
      - name: Install dependencies
        run: poetry install
      
      - name: Run ETL (prepare data)
        run: poetry run python prepare_data.py

      - name: Save dataset as artifact
        uses: actions/upload-artifact@v6
        with:
          name: dataset
          path: dataset_processed.csv
  
  training-model:
    needs: preparing-data
    name: Training Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: dataset

      - name: Verify downloaded artifact
        run: |
          echo "Content of the downloaded artifact: "
          ls -la
          echo "Reading the first few lines of the dataset: "
          cat dataset_processed.csv | head -n 5